import AsyncStorage from '@react-native-async-storage/async-storage';
import { Link } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { FerioHeader } from '@/components/FerioHeader';
import { formatTaka } from '@/lib/catalog';
import { colors, radii } from '@/lib/theme';
import { useCart } from '@/state/cart';

const STORAGE_KEY='ferio_mobile_checkout_details_v1';
const initial={name:'',phone:'',email:'',district:'',area:'',detailedAddress:'',landmark:'',customerNote:'',marketingConsent:false,purchaseActivityConsent:false,termsAccepted:false,paymentMethod:'COD' as 'COD'|'PREPAID'};
export default function CheckoutScreen(){
 const {items,subtotal}=useCart(); const [form,setForm]=useState(initial); const deliveryFee=12000; const total=useMemo(()=>subtotal+deliveryFee,[subtotal]);
 useEffect(()=>{AsyncStorage.getItem(STORAGE_KEY).then(raw=>{if(raw)setForm({...initial,...JSON.parse(raw)})}).catch(()=>{})},[]); useEffect(()=>{AsyncStorage.setItem(STORAGE_KEY,JSON.stringify(form)).catch(()=>{})},[form]);
 const field=(key:keyof typeof form,label:string,placeholder:string,opts?:{keyboardType?:'default'|'phone-pad'|'email-address';multiline?:boolean})=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={String(form[key]??'')} onChangeText={v=>setForm(s=>({...s,[key]:v}))} placeholder={placeholder} placeholderTextColor='#9a9a9e' keyboardType={opts?.keyboardType} multiline={opts?.multiline} style={[styles.input,opts?.multiline&&styles.textarea]}/></View>;
 return <SafeAreaView style={styles.safe}><FerioHeader/><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps='handled'>
   <Text style={styles.eyebrow}>CHECKOUT</Text><Text style={styles.title}>Delivery details</Text><Text style={styles.copy}>Your final delivery fee, stock and payment availability must be calculated by the NestJS checkout preview before an order is placed.</Text>
   <View style={styles.form}>{field('name','Full name','Your name')}{field('phone','Mobile number','01XXXXXXXXX',{keyboardType:'phone-pad'})}{field('email','Email (optional)','you@example.com',{keyboardType:'email-address'})}{field('district','District','Dhaka')}{field('area','Area / upazila','Your delivery area')}{field('detailedAddress','Detailed address','House, road, block, floor',{multiline:true})}{field('landmark','Landmark (optional)','Nearby landmark')}{field('customerNote','Order note (optional)','Delivery instructions',{multiline:true})}</View>
   <View style={styles.section}><Text style={styles.sectionTitle}>Payment</Text><View style={styles.paymentRow}><Pressable onPress={()=>setForm(s=>({...s,paymentMethod:'COD'}))} style={[styles.payment,form.paymentMethod==='COD'&&styles.paymentActive]}><Text style={[styles.paymentText,form.paymentMethod==='COD'&&styles.paymentTextActive]}>Cash on delivery</Text></Pressable><Pressable onPress={()=>setForm(s=>({...s,paymentMethod:'PREPAID'}))} style={[styles.payment,form.paymentMethod==='PREPAID'&&styles.paymentActive]}><Text style={[styles.paymentText,form.paymentMethod==='PREPAID'&&styles.paymentTextActive]}>Prepaid</Text></Pressable></View></View>
   <View style={styles.section}><Text style={styles.sectionTitle}>Consent</Text><Toggle label='Send me product and offer updates' value={form.marketingConsent} onValueChange={v=>setForm(s=>({...s,marketingConsent:v}))}/><Toggle label='Allow anonymized purchase activity notices' value={form.purchaseActivityConsent} onValueChange={v=>setForm(s=>({...s,purchaseActivityConsent:v}))}/><Toggle label='I accept terms, privacy and return conditions' value={form.termsAccepted} onValueChange={v=>setForm(s=>({...s,termsAccepted:v}))}/></View>
   <View style={styles.summary}><Text style={styles.sectionTitle}>Order summary</Text><View style={styles.summaryRow}><Text style={styles.muted}>Items ({items.reduce((n,i)=>n+i.quantity,0)})</Text><Text style={styles.value}>{formatTaka(subtotal)}</Text></View><View style={styles.summaryRow}><Text style={styles.muted}>Example delivery fee</Text><Text style={styles.value}>{formatTaka(deliveryFee)}</Text></View><View style={[styles.summaryRow,styles.totalRow]}><Text style={styles.totalLabel}>Estimated total</Text><Text style={styles.total}>{formatTaka(total)}</Text></View><Text style={styles.notice}>This screen mirrors the website form structure. Production mobile checkout still needs the explicit mobile cart/session contract and server checkout preview.</Text></View>
   <Pressable disabled={!items.length||!form.termsAccepted} style={[styles.place,(!items.length||!form.termsAccepted)&&styles.disabled]}><Text style={styles.placeText}>Preview & place order</Text></Pressable><Link href='/(tabs)/cart'><Text style={styles.back}>← Back to cart</Text></Link>
 </ScrollView></SafeAreaView>;
}
function Toggle({label,value,onValueChange}:{label:string;value:boolean;onValueChange:(v:boolean)=>void}){return <View style={styles.toggle}><Text style={styles.toggleText}>{label}</Text><Switch value={value} onValueChange={onValueChange} trackColor={{false:'#dedee1',true:'#2b2b2f'}} thumbColor='#fff'/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:18,paddingBottom:70},eyebrow:{fontSize:10,letterSpacing:1.2,color:colors.ink2,fontWeight:'600'},title:{marginTop:7,fontSize:30,fontWeight:'600',letterSpacing:-.8,color:colors.ink},copy:{marginTop:10,maxWidth:520,fontSize:13,lineHeight:20,color:colors.ink2},form:{marginTop:28,gap:15},field:{gap:7},label:{fontSize:12,color:colors.ink2},input:{borderWidth:1,borderColor:colors.line,borderRadius:radii.card,paddingHorizontal:14,paddingVertical:12,fontSize:14,color:colors.ink,backgroundColor:'#fff'},textarea:{minHeight:82,textAlignVertical:'top'},section:{marginTop:30,borderTopWidth:1,borderTopColor:colors.line,paddingTop:22},sectionTitle:{fontSize:16,fontWeight:'500',color:colors.ink},paymentRow:{marginTop:14,flexDirection:'row',gap:8},payment:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingVertical:11,alignItems:'center'},paymentActive:{backgroundColor:colors.ink,borderColor:colors.ink},paymentText:{fontSize:12,color:colors.ink2},paymentTextActive:{color:'#fff'},toggle:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:16,borderBottomWidth:1,borderBottomColor:colors.line},toggleText:{flex:1,fontSize:12.5,lineHeight:18,color:colors.ink2},summary:{marginTop:30,borderWidth:1,borderColor:colors.line,borderRadius:radii.card,padding:17,gap:11},summaryRow:{flexDirection:'row',justifyContent:'space-between',gap:12},muted:{fontSize:12,color:colors.ink2},value:{fontSize:12,color:colors.ink},totalRow:{borderTopWidth:1,borderTopColor:colors.line,paddingTop:12,marginTop:3},totalLabel:{fontSize:14,fontWeight:'600',color:colors.ink},total:{fontSize:16,fontWeight:'600',color:colors.ink},notice:{fontSize:11,lineHeight:16,color:colors.ink2},place:{marginTop:22,backgroundColor:colors.ink,borderRadius:radii.pill,paddingVertical:14,alignItems:'center'},disabled:{opacity:.25},placeText:{color:'#fff',fontSize:14,fontWeight:'600'},back:{marginTop:18,textAlign:'center',fontSize:12,color:colors.ink2}});
