import { useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { FerioHeader } from '@/components/FerioHeader';
import { colors, radii } from '@/lib/theme';
const stages=['Order received','Order confirmed','Processing','Out for delivery','Delivered'];
export default function TrackScreen(){const p=useLocalSearchParams<{reference?:string}>();const [reference,setReference]=useState(p.reference||'');const [phone,setPhone]=useState('');const [demo,setDemo]=useState(false);return <SafeAreaView style={styles.safe}><FerioHeader/><ScrollView contentContainerStyle={styles.container}>
 <Text style={styles.eyebrow}>DELIVERY STATUS</Text><Text style={styles.title}>Track your order</Text><Text style={styles.copy}>Enter the order reference from your confirmation and the same phone number used at checkout.</Text>
 <View style={styles.form}><Text style={styles.label}>Order reference</Text><TextInput value={reference} onChangeText={setReference} autoCapitalize='characters' placeholder='FER-260806-ABC123' placeholderTextColor='#9a9a9e' style={styles.input}/><Text style={styles.label}>Checkout phone</Text><TextInput value={phone} onChangeText={setPhone} keyboardType='phone-pad' placeholder='01XXXXXXXXX' placeholderTextColor='#9a9a9e' style={styles.input}/><Pressable onPress={()=>setDemo(true)} style={styles.button}><Text style={styles.buttonText}>Track order</Text></Pressable></View>
 <View style={styles.result}>{demo?<><View style={styles.resultTop}><View><Text style={styles.ref}>{reference||'FER-260806-ABC123'}</Text><Text style={styles.status}>Processing</Text></View><Text style={styles.meta}>Verified order</Text></View><View style={styles.courier}><View><Text style={styles.smallMuted}>Courier</Text><Text style={styles.small}>Being assigned</Text></View><View><Text style={styles.smallMuted}>Tracking number</Text><Text style={styles.small}>Pending</Text></View></View><View style={styles.timeline}>{stages.map((s,i)=><View key={s} style={styles.stage}><View style={[styles.dot,i<3&&styles.dotDone]}/><View style={[styles.stageCard,i>=3&&styles.stagePending]}><Text style={[styles.stageText,i>=3&&styles.pendingText]}>{s}</Text><Text style={styles.when}>{i<3?'Updated':'Pending'}</Text></View></View>)}</View></>:<View style={styles.emptyResult}><Text style={styles.emptyText}>Verified tracking updates will appear here. Ferio never exposes order details from a reference alone.</Text></View>}</View>
 </ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:18,paddingBottom:70},eyebrow:{fontSize:10,letterSpacing:1.2,color:colors.ink2,fontWeight:'600'},title:{marginTop:8,fontSize:34,fontWeight:'600',letterSpacing:-1,color:colors.ink},copy:{marginTop:10,maxWidth:480,fontSize:14,lineHeight:22,color:colors.ink2},form:{marginTop:26,gap:8},label:{marginTop:7,fontSize:12,color:colors.ink2},input:{borderWidth:1,borderColor:colors.line,borderRadius:radii.card,paddingHorizontal:14,paddingVertical:12,fontSize:14,color:colors.ink},button:{marginTop:10,alignSelf:'flex-start',backgroundColor:colors.ink,borderRadius:radii.pill,paddingHorizontal:20,paddingVertical:11},buttonText:{color:'#fff',fontSize:12,fontWeight:'600'},result:{marginTop:32,borderWidth:1,borderColor:colors.line,borderRadius:radii.card,padding:17,minHeight:290},emptyResult:{flex:1,minHeight:250,alignItems:'center',justifyContent:'center'},emptyText:{maxWidth:360,textAlign:'center',fontSize:13,lineHeight:21,color:colors.ink2},resultTop:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingBottom:16,borderBottomWidth:1,borderBottomColor:colors.line},ref:{fontSize:10,letterSpacing:1.1,color:colors.ink2},status:{marginTop:6,fontSize:23,fontWeight:'600',color:colors.ink},meta:{fontSize:11,color:colors.ink2},courier:{marginTop:16,flexDirection:'row',justifyContent:'space-between',backgroundColor:'#f7f7f7',padding:13,borderRadius:radii.card},smallMuted:{fontSize:10,color:colors.ink2},small:{marginTop:4,fontSize:12,color:colors.ink},timeline:{marginTop:24,gap:10},stage:{flexDirection:'row',gap:10,alignItems:'stretch'},dot:{marginTop:12,width:12,height:12,borderRadius:6,borderWidth:2,borderColor:colors.line,backgroundColor:'#fff'},dotDone:{backgroundColor:colors.ink,borderColor:colors.ink},stageCard:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:radii.card,padding:12},stagePending:{opacity:.35,backgroundColor:colors.surface},stageText:{fontSize:12,fontWeight:'600',color:colors.ink},pendingText:{color:colors.ink2},when:{marginTop:4,fontSize:10,color:colors.ink2}});
