import { Link } from 'expo-router';
import { Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FerioHeader } from '@/components/FerioHeader';
import { formatTaka } from '@/lib/catalog';
import { colors, radii } from '@/lib/theme';
import { useCart } from '@/state/cart';

export default function CartScreen(){const {items,subtotal,updateQuantity,remove}=useCart(); return <SafeAreaView style={styles.safe}><FerioHeader/><ScrollView contentContainerStyle={styles.container}>
 <Text style={styles.title}>{items.length?'Your cart':'Your cart is empty'}</Text><Text style={styles.subtitle}>{items.length?'Prices and availability are checked again before checkout.':'Add a product to keep it here on this device.'}</Text>
 {!items.length?<Link href='/(tabs)/products' asChild><Pressable style={styles.primary}><Text style={styles.primaryText}>Browse products</Text></Pressable></Link>:<>
 <View style={styles.list}>{items.map(item=><View key={item.variantId} style={styles.item}>{item.image?<Image source={{uri:item.image}} style={styles.image}/>:<View style={styles.image}/>}<View style={styles.detail}><Text style={styles.name}>{item.name}</Text><Text style={styles.price}>{formatTaka(item.price)}</Text><View style={styles.controls}><View style={styles.stepper}><Pressable onPress={()=>updateQuantity(item.variantId,item.quantity-1)} style={styles.step}><Text style={styles.stepText}>−</Text></Pressable><Text style={styles.qty}>{item.quantity}</Text><Pressable onPress={()=>updateQuantity(item.variantId,item.quantity+1)} style={styles.step}><Text style={styles.stepText}>+</Text></Pressable></View><Pressable onPress={()=>remove(item.variantId)}><Text style={styles.remove}>Remove</Text></Pressable></View></View><Text style={styles.lineTotal}>{formatTaka(item.price*item.quantity)}</Text></View>)}</View>
 <View style={styles.summary}><View style={styles.summaryRow}><Text style={styles.summaryMuted}>Estimated subtotal</Text><Text style={styles.summaryValue}>{formatTaka(subtotal)}</Text></View><Text style={styles.note}>Delivery, discounts, and final stock are calculated again during checkout.</Text><View style={styles.buttons}><Link href='/(tabs)/products' asChild><Pressable style={styles.secondary}><Text style={styles.secondaryText}>Continue shopping</Text></Pressable></Link><Link href='/checkout' asChild><Pressable style={styles.primaryFlex}><Text style={styles.primaryText}>Proceed to checkout</Text></Pressable></Link></View></View></>}
 </ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:18,paddingBottom:60},title:{fontSize:28,fontWeight:'600',letterSpacing:-.7,color:colors.ink},subtitle:{marginTop:5,fontSize:13,color:colors.ink2,lineHeight:19},list:{marginTop:28,borderTopWidth:1,borderTopColor:colors.line},item:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:18,borderBottomWidth:1,borderBottomColor:colors.line},image:{width:72,height:80,borderRadius:radii.card,backgroundColor:colors.surface},detail:{flex:1},name:{fontSize:14,fontWeight:'500',color:colors.ink},price:{marginTop:4,fontSize:12,color:colors.ink2},controls:{marginTop:10,flexDirection:'row',alignItems:'center',gap:12},stepper:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:colors.line,borderRadius:radii.pill},step:{paddingHorizontal:10,paddingVertical:5},stepText:{color:colors.ink2,fontSize:14},qty:{width:24,textAlign:'center',fontSize:12,color:colors.ink},remove:{fontSize:11,color:colors.ink2,textDecorationLine:'underline'},lineTotal:{fontSize:13,fontWeight:'500',color:colors.ink},summary:{marginTop:26},summaryRow:{flexDirection:'row',justifyContent:'space-between'},summaryMuted:{fontSize:13,color:colors.ink2},summaryValue:{fontSize:14,fontWeight:'500',color:colors.ink},note:{marginTop:12,borderTopWidth:1,borderTopColor:colors.line,paddingTop:12,fontSize:12,lineHeight:18,color:colors.ink2},buttons:{marginTop:18,flexDirection:'row',gap:8},secondary:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingVertical:12,alignItems:'center'},secondaryText:{fontSize:12,fontWeight:'500',color:colors.ink},primaryFlex:{flex:1,backgroundColor:colors.ink,borderRadius:radii.pill,paddingVertical:12,alignItems:'center'},primary:{alignSelf:'center',marginTop:26,backgroundColor:colors.ink,borderRadius:radii.pill,paddingHorizontal:22,paddingVertical:12},primaryText:{color:'#fff',fontSize:12,fontWeight:'600'}});
