export type CommerceSettings = {
  id: string;
  storeName: string;
  legalName: string | null;
  supportPhone: string | null;
  supportEmail: string | null;
  currency: "BDT";
  timezone: string;
  orderPrefix: string;
  defaultReturnWindowDays: number | null;
  codEnabled: boolean;
  prepaidEnabled: boolean;
  serviceBookingEnabled: boolean;
  warrantyClaimsEnabled: boolean;
  storefrontAnalyticsEnabled: boolean;
  purchaseActivityEnabled: boolean;
  purchaseHistoryEnabled: boolean;
  purchaseActivityShowDistrict: boolean;
  purchaseActivityShowArea: boolean;
  purchaseActivityDurationMs: number;
  purchaseActivityIntervalSeconds: number;
  purchaseActivityMaxAgeDays: number;
  purchaseActivityExcludedProductIds: string[];
  categoryTopNavEnabled: boolean;
  categorySideNavEnabled: boolean;
  termsUrl: string | null;
  privacyUrl: string | null;
  returnPolicyUrl: string | null;
  createdAt: string;
  updatedAt: string;
};
