import { useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FerioHeader } from '@/components/FerioHeader';
import { getProduct, formatTaka } from '@/lib/catalog';
import { colors, radii } from '@/lib/theme';
import { useCart } from '@/state/cart';
import type { CatalogProduct } from '@/types/catalog';

export default function ProductDetailScreen(){
 const {slug}=useLocalSearchParams<{slug:string}>(); const [product,setProduct]=useState<CatalogProduct|null>(null); const [selected,setSelected]=useState<string>(''); const {add}=useCart();
 useEffect(()=>{if(slug)getProduct(slug).then(p=>{setProduct(p);setSelected(p.variantId)}).catch(()=>setProduct(null));},[slug]);
 const displayed=useMemo(()=>{if(!product)return null; const v=product.variants.find(v=>v.id===selected); return v?{...product,variantId:v.id,sku:v.sku,price:v.price,compareAtPrice:v.compareAtPrice,availableStock:v.availableStock,selectedVariantName:v.name}:product},[product,selected]);
 if(!displayed)return <SafeAreaView style={styles.safe}><FerioHeader/><ActivityIndicator style={{marginTop:60}}/></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><FerioHeader/><ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
   {displayed.image?<Image source={{uri:displayed.image}} style={styles.hero}/>:<View style={[styles.hero,styles.placeholder]}><Text style={styles.muted}>Product image coming soon</Text></View>}
   {displayed.images.length>1?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.thumbs}>{displayed.images.slice(1,5).map((img,i)=><Image key={`${img}-${i}`} source={{uri:img}} style={styles.thumb}/>)}</ScrollView>:null}
   <Text style={styles.category}>{displayed.category.name}</Text><Text style={styles.title}>{displayed.name}</Text>{displayed.brand?<Text style={styles.brand}>By {displayed.brand}</Text>:null}
   {displayed.condition==='SECOND_HAND'?<View style={styles.condition}><View style={styles.conditionRow}><Text style={styles.conditionTitle}>Second-hand product</Text><View style={styles.conditionPill}><Text style={styles.conditionPillText}>{displayed.conditionGrade?.replaceAll('_',' ').toLowerCase()}</Text></View></View><Text style={styles.conditionNote}>{displayed.conditionNote}</Text></View>:null}
   <View style={styles.priceRow}><Text style={styles.price}>{formatTaka(displayed.price)}</Text>{displayed.compareAtPrice?<Text style={styles.compare}>{formatTaka(displayed.compareAtPrice)}</Text>:null}</View>
   <Text style={styles.description}>{displayed.description}</Text>
   {displayed.variants.length>1?<><Text style={styles.variantLabel}>Choose variant</Text><View style={styles.variants}>{displayed.variants.map(v=><Pressable key={v.id} onPress={()=>setSelected(v.id)} style={[styles.variant,v.id===selected&&styles.variantActive]}><Text style={[styles.variantText,v.id===selected&&styles.variantTextActive]}>{v.name}</Text></Pressable>)}</View></>:null}
   <View style={styles.info}><Text style={styles.infoText}>{displayed.codAvailable?'Cash on delivery available':'Prepaid only'}</Text>{displayed.deliveryNote?<Text style={styles.infoText}>{displayed.deliveryNote}</Text>:null}{displayed.returnNote?<Text style={styles.infoText}>{displayed.returnNote}</Text>:null}<Text style={styles.infoText}>{displayed.availableStock>0?`${displayed.availableStock} available`:'Currently out of stock'}</Text></View>
   <Pressable disabled={displayed.availableStock<=0} onPress={()=>add(displayed)} style={[styles.add,displayed.availableStock<=0&&styles.disabled]}><Text style={styles.addText}>{displayed.availableStock>0?'Add to cart':'Out of stock'}</Text></Pressable>
   <View style={styles.section}><Text style={styles.sectionTitle}>Product features</Text><Text style={styles.sectionCopy}>Feature content from the web product-content module can be mapped here as native rows or cards.</Text></View>
   <View style={styles.section}><Text style={styles.sectionTitle}>Customer reviews</Text><Text style={styles.sectionCopy}>Verified review summaries, media reviews and product Q&A can use the same NestJS endpoints as the web storefront.</Text></View>
   <View style={styles.section}><Text style={styles.sectionTitle}>Related products</Text><Text style={styles.sectionCopy}>Related products should be loaded by category and rendered as a horizontal native product rail.</Text></View>
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:18,paddingBottom:70},hero:{width:'100%',aspectRatio:.8,borderRadius:radii.card,backgroundColor:colors.surface,resizeMode:'cover'},placeholder:{alignItems:'center',justifyContent:'center'},muted:{color:colors.ink2,fontSize:12},thumbs:{gap:10,marginTop:10},thumb:{width:72,height:72,borderRadius:radii.card,backgroundColor:colors.surface},category:{marginTop:22,color:colors.ink2,fontSize:13},title:{marginTop:4,color:colors.ink,fontSize:26,lineHeight:31,fontWeight:'600',letterSpacing:-.7},brand:{marginTop:6,color:colors.ink2,fontSize:13},condition:{marginTop:20,borderWidth:1,borderColor:colors.line,borderRadius:radii.card,padding:14},conditionRow:{flexDirection:'row',justifyContent:'space-between',gap:10,alignItems:'center'},conditionTitle:{color:colors.ink,fontSize:13,fontWeight:'500'},conditionPill:{backgroundColor:colors.surface,borderRadius:radii.pill,paddingHorizontal:9,paddingVertical:5},conditionPillText:{color:colors.ink2,fontSize:10},conditionNote:{marginTop:8,color:colors.ink2,fontSize:12,lineHeight:18},priceRow:{marginTop:20,flexDirection:'row',alignItems:'baseline',gap:10},price:{fontSize:22,fontWeight:'600',color:colors.ink},compare:{fontSize:14,color:colors.ink2,textDecorationLine:'line-through'},description:{marginTop:20,color:colors.ink2,fontSize:14,lineHeight:22},variantLabel:{marginTop:24,color:colors.ink,fontSize:13,fontWeight:'500'},variants:{marginTop:10,flexDirection:'row',flexWrap:'wrap',gap:8},variant:{borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:14,paddingVertical:8},variantActive:{backgroundColor:colors.ink,borderColor:colors.ink},variantText:{fontSize:12,color:colors.ink2},variantTextActive:{color:'#fff'},info:{marginTop:26,borderTopWidth:1,borderTopColor:colors.line,paddingTop:20,gap:8},infoText:{fontSize:13,color:'#3f3f43'},add:{marginTop:24,backgroundColor:colors.ink,borderRadius:radii.pill,paddingVertical:14,alignItems:'center'},disabled:{opacity:.3},addText:{color:'#fff',fontSize:14,fontWeight:'600'},section:{marginTop:36,borderTopWidth:1,borderTopColor:colors.line,paddingTop:24},sectionTitle:{fontSize:18,fontWeight:'600',color:colors.ink,letterSpacing:-.3},sectionCopy:{marginTop:8,color:colors.ink2,fontSize:13,lineHeight:20}});
